const $ = s => document.querySelector(s);
const canvas = $('#canvas'); const ctx = canvas.getContext('2d'); const toastEl = $('#toast');
let tool = 'rect', operations = [], history = [], cropSelection = null, dragStart = null, dragCurrent = null, baseImage = new Image(), originalImageSrc = '', step = null;
const params = new URLSearchParams(location.search); const stepId = params.get('id');
function toast(msg){toastEl.textContent=msg;toastEl.hidden=false;clearTimeout(toastEl.t);toastEl.t=setTimeout(()=>toastEl.hidden=true,2200)}
function cloneOps(){return JSON.parse(JSON.stringify(operations))} function pushHistory(){history.push({operations:cloneOps(),cropSelection:cropSelection?{...cropSelection}:null});if(history.length>30)history.shift()}
function rectFrom(a,b){return{x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),w:Math.abs(a.x-b.x),h:Math.abs(a.y-b.y)}}
function pos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*(canvas.width/r.width),y:(e.clientY-r.top)*(canvas.height/r.height)}}
function drawArrow(op){const angle=Math.atan2(op.y2-op.y1,op.x2-op.x1),head=16;ctx.save();ctx.strokeStyle='#ef4444';ctx.fillStyle='#ef4444';ctx.lineWidth=5;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(op.x1,op.y1);ctx.lineTo(op.x2,op.y2);ctx.stroke();ctx.beginPath();ctx.moveTo(op.x2,op.y2);ctx.lineTo(op.x2-head*Math.cos(angle-Math.PI/6),op.y2-head*Math.sin(angle-Math.PI/6));ctx.lineTo(op.x2-head*Math.cos(angle+Math.PI/6),op.y2-head*Math.sin(angle+Math.PI/6));ctx.closePath();ctx.fill();ctx.restore()}
function drawMosaic(op){const sx=Math.max(0,Math.round(op.x)),sy=Math.max(0,Math.round(op.y)),sw=Math.min(canvas.width-sx,Math.max(1,Math.round(op.w))),sh=Math.min(canvas.height-sy,Math.max(1,Math.round(op.h)));if(sw<1||sh<1)return;const data=ctx.getImageData(sx,sy,sw,sh),size=14;for(let y=0;y<sh;y+=size)for(let x=0;x<sw;x+=size){const p=((Math.min(y,sh-1)*sw)+Math.min(x,sw-1))*4;ctx.fillStyle=`rgba(${data.data[p]},${data.data[p+1]},${data.data[p+2]},1)`;ctx.fillRect(sx+x,sy+y,Math.min(size,sw-x),Math.min(size,sh-y))}}
function drawMarker(){if(!step?.click)return;const x=step.click.x/(step.click.viewportWidth||1)*canvas.width,y=step.click.y/(step.click.viewportHeight||1)*canvas.height;ctx.save();ctx.strokeStyle='#ef4444';ctx.fillStyle='#ef4444';ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,8,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(x,y,2.5,0,Math.PI*2);ctx.fill();ctx.restore()}
function render(showUi=true){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(baseImage,0,0,canvas.width,canvas.height);drawMarker();for(const op of operations){if(op.type==='rect'){ctx.save();ctx.strokeStyle='#ef4444';ctx.lineWidth=5;ctx.strokeRect(op.x,op.y,op.w,op.h);ctx.restore()}else if(op.type==='arrow')drawArrow(op);else if(op.type==='mosaic')drawMosaic(op)}if(showUi&&cropSelection){ctx.save();ctx.strokeStyle='#2563eb';ctx.setLineDash([10,6]);ctx.lineWidth=4;ctx.strokeRect(cropSelection.x,cropSelection.y,cropSelection.w,cropSelection.h);ctx.restore()}if(showUi&&dragStart&&dragCurrent){const r=rectFrom(dragStart,dragCurrent);ctx.save();ctx.strokeStyle=tool==='crop'?'#2563eb':'#ef4444';ctx.setLineDash([8,5]);ctx.lineWidth=3;if(tool==='arrow')drawArrow({x1:dragStart.x,y1:dragStart.y,x2:dragCurrent.x,y2:dragCurrent.y});else ctx.strokeRect(r.x,r.y,r.w,r.h);ctx.restore()}}
function setTool(next){tool=next;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));$('#help').textContent={rect:'赤枠：強調したい範囲をドラッグしてください。',arrow:'矢印：始点から終点までドラッグしてください。',mosaic:'モザイク：隠したい範囲をドラッグしてください。',crop:'切り抜き：残したい範囲をドラッグし、「切り抜きを適用」を押してください。'}[tool]}
canvas.addEventListener('pointerdown',e=>{dragStart=pos(e);dragCurrent=dragStart;canvas.setPointerCapture(e.pointerId);render()});canvas.addEventListener('pointermove',e=>{if(!dragStart)return;dragCurrent=pos(e);render()});canvas.addEventListener('pointerup',e=>{if(!dragStart)return;dragCurrent=pos(e);const r=rectFrom(dragStart,dragCurrent);if(r.w<5&&r.h<5){dragStart=dragCurrent=null;return render()}pushHistory();if(tool==='arrow')operations.push({type:'arrow',x1:dragStart.x,y1:dragStart.y,x2:dragCurrent.x,y2:dragCurrent.y});else if(tool==='crop')cropSelection=r;else operations.push({type:tool,...r});dragStart=dragCurrent=null;render()});
document.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>setTool(b.dataset.tool)));
$('#undo').onclick=()=>{const last=history.pop();if(!last)return toast('戻せる編集がありません。');operations=last.operations;cropSelection=last.cropSelection;render()};
$('#reset').onclick=()=>{if(!confirm('画像編集を最初の状態へ戻しますか？'))return;operations=[];history=[];cropSelection=null;step.click=step.originalClick||step.click;baseImage=new Image();baseImage.onload=()=>{canvas.width=baseImage.naturalWidth;canvas.height=baseImage.naturalHeight;render()};baseImage.src=originalImageSrc};
$('#applyCrop').onclick=()=>{if(!cropSelection)return toast('切り抜く範囲を選択してください。');render(false);const r=cropSelection,tmp=document.createElement('canvas');tmp.width=Math.max(1,Math.round(r.w));tmp.height=Math.max(1,Math.round(r.h));tmp.getContext('2d').drawImage(canvas,r.x,r.y,r.w,r.h,0,0,tmp.width,tmp.height);baseImage=new Image();baseImage.onload=()=>{canvas.width=baseImage.naturalWidth;canvas.height=baseImage.naturalHeight;operations=[];cropSelection=null;step.click=null;render()};baseImage.src=tmp.toDataURL('image/png')};
$('#save').onclick=async()=>{render(false);const res=await chrome.runtime.sendMessage({type:'manualclip_update_step_image',id:stepId,image:canvas.toDataURL('image/png'),clearClick:true});if(!res?.ok)return toast(res?.error||'保存に失敗しました。');window.close()};
(async()=>{const res=await chrome.runtime.sendMessage({type:'manualclip_get_state'});step=res?.state?.steps?.find(s=>s.id===stepId);if(!step)return toast('対象の手順が見つかりません。');step.originalClick=step.click?JSON.parse(JSON.stringify(step.click)):null;originalImageSrc=step.image;baseImage.onload=()=>{canvas.width=baseImage.naturalWidth;canvas.height=baseImage.naturalHeight;render()};baseImage.src=step.image;setTool('rect')})().catch(e=>toast(e.message));
